[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft_anchor = "2Pmx31wm2PWABi7GgwjkJfMexFxwXeAU8KvvEE42UA9V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/i/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
